version: "3.8"
services:
  laravel_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_svc1
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_host
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./src/public:/var/www/html
    networks:
      laravel_net:
        aliases:
          - laravel_host1
volumes:
  src: {}
networks:
  laravel_net:
    name: network_laravel_net
    driver: bridge
